### GENERAL SETTINGS ###

# Site settings
title: Paolo Caracciolo
description: "Designer"
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://www.paolocaracciolo.com"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is
responsive_classes: 
 - xl
 - lg
 - md
 - sm
 - xs